# Setup
title:               My blog!
tagline:             'My blog!'
description:         'My blog!'
url:                 https://nvladimiroff.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nick Vladimiroff

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
