# Setup
title:               Code and Cake
url:                 https://codeandcake.dev
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Nick Vladimiroff

# Gems
plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
